# Generated by Django 4.1 on 2022-11-09 20:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_food_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.food')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restaurant')),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart',
            field=models.ManyToManyField(to='core.foodcart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ManyToManyField(to='core.foodcart'),
        ),
    ]
